version: '3.8'
services:
  backend:
    build:
      context: .
      dockerfile: ./api-server/Dockerfile
      args:
        PORT: ${API_SERVER_PORT}
        SESC_REQUEST_LOCK_DELAY: ${SESC_REQUEST_LOCK_DELAY}
        SCHEDULES_MAX_PARALLEL_REQUESTS: ${SESC_REQUEST_LOCK_DELAY}
        GRAPHQL_LANDING_PAGE: ${GRAPHQL_LANDING_PAGE}
        SCHEDULING_TZ: ${SCHEDULING_TZ}
    ports:
      - ${API_SERVER_PORT}:${API_SERVER_PORT}
    restart: always
  frontend:
    build:
      context: .
      dockerfile: ./frontend/Dockerfile
    ports:
      - '3030:3030'
    restart: always
  cache:
    image: redis:6.2-alpine
    restart: always
    ports:
      - '6379:6379'
    command: redis-server --save 20 1 --loglevel warning
    volumes:
      - cache:/data
  worker:
    build:
      context: .
      dockerfile: ./worker/Dockerfile
    restart: always
  nginx:
    build:
      context: .
      dockerfile: ./nginx/Dockerfile
      args:
        NGINX_PORT: '3333'
        FRONTEND_PORT: '3030'
        BACKEND_PORT: ${API_SERVER_PORT}
    restart: always
    ports:
      - ${NGINX_PORT}:80

volumes:
  cache:
    driver: local